name: API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      api:
        build:
          context: .
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run API (background)
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
      - name: Run Postman tests
        run: |
          npm install -g newman
          newman run tests/test_api.postman_collection.json --insecure
      - name: Run Playwright tests
        run: |
          cd tests/playwright
          npm ci
          npx playwright install --with-deps
          npx playwright test ../example.spec.ts
      - name: Run Cypress tests
        run: |
          cd tests/cypress
          npm ci
          npx cypress run --spec '../example.cy.js'
