name: API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Postman CLI
        run: |
          npm install -g newman
      - name: Run API (background)
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
      - name: Run Postman tests
        run: |
          newman run tests/test_api.postman_collection.json --insecure
      - name: Run Playwright tests
        run: |
          cd tests/playwright
          npm install
          npx playwright install --with-deps
          npm test
      - name: Run Cypress tests
        run: |
          cd tests/cypress
          npm install
          npm test
